### ISSUE TITLE
Do not invalidate NpyFile

### ISSUE THREAD

**Issue by Shatur** [ExpHP/npyz#55]
Currently [data](https://docs.rs/npyz/latest/npyz/struct.NpyFile.html#method.data) consumes `NpyFile`. But it's quite uncommon for iterators. It would be great to just keep reference to the `NpyFile` in `NpyReader`.

**Comment by ExpHP** [comment]
It's because NpyReader is built around `io::Read`.  E.g. it could be reading a byte stream from a named pipe which is not seekable.  This is comparable to [`std::io::BufRead::lines`](https://doc.rust-lang.org/stable/std/io/struct.Lines.html).

Can I see an example of code where consuming the reader is problematic?  Maybe there is another solution.

**Comment by Shatur** [comment]
> It's because NpyReader is built around io::Read.

Sure, my suggestion is just use a reference instead of store a value.

> Can I see an example of code where consuming the reader is problematic? Maybe there is another solution.

Not very problematic. I implementing [ChipWhisperer](https://pypi.org/project/chipwhisperer) format which consists of several NumPy files. And I have to store parsed files in a struct to provide a non-consuming iterator for an interface. Currently I just store memory mapped files and create `NpyReader` every time. But it would be great to avoid parsing files every time by making `NpyReader` non-consumable.

**Comment by ExpHP** [comment]
> Sure, my suggestion is just use a reference instead of store a value.

Not sure I understand.  It's not possible to use a `&R` as that does not `impl Read`, and if it took a `&mut R` then it would only be possible to read the file once (and then it would only be able to give an empty iterator afterwards), unless some seeking was done.

>  Currently I just store memory mapped files and create NpyReader every time. But it would be great to avoid parsing files every time by making NpyReader non-consumable.

I would expect that the handles to your memory-mapped IO are cheaply clonable.  Would it suffice to `impl<R> Clone for NpyReader<R> where R: Clone`?

**Comment by Shatur** [comment]
> It's not possible to use a &R as that does not impl Read

No, no, I meant instead of consuming `NpyFile` here:

https://github.com/ExpHP/npyz/blob/c9b8213ca9e8dc28ef4c6e362a86ff43b657e5d6/src/read.rs#L199-L202

Just store a reference to it for reading inside `NpyReader`.

> I would expect that the handles to your memory-mapped IO are cheaply clonable. Would it suffice to impl<R> Clone for NpyReader<R> where R: Clone?

Actually this will work too...

**Comment by ExpHP** [comment]
> Just store a reference to it for reading inside NpyReader.

The issue is the same.  Storing `&NpyFile` gives access to `&R` and storing `&mut NpyFile` only gives access to `&mut R`.  Calling `.data().collect()` twice is invariably going to give junk.

---

I challenge the statement that consuming is "uncommon" for iterators.  Consuming is the natural state of an iterator in rust, because iteration mutates; even `for` loop syntax desugars to `into_iter`.  Types like `Vec` and `HashSet` may provide `iter()` methods that borrow, but what's different about those types is that they are data structures.

NpyFile is not a data structure, but rather, an IO adapter.  It represents a readable NPY byte stream, in the state immediately after its header bytes have been read, but before any data bytes have been read.  Iterating through `data()` can have side-effects that make the NpyFile not reusable; for instance, when reading `NpyFile<zip::read::ZipFile<'a>>`s to extract .NPYs from an .NPZ, iterating the data will modify the internal state of the zip decoder.

Implementing Clone is standard practice for representing the idea of "repeatable iteration."  Notice how even [`Iterator::cycle`](https://doc.rust-lang.org/std/iter/trait.Iterator.html) uses this, via a `Self: Clone` bound.

(On that note, I am going to impl Clone for `NpyReader` as well)

**Comment by ExpHP** [comment]
> (On that note, I am going to impl Clone for NpyReader as well)

Oops.  There's a `<T as Deserialize>::TypeReader` field, which is a problem for types that use `Box<dyn TypeReadDyn>`.  Welp.  Guess it's just going to be for NpyFile.

**Comment by ExpHP** [comment]
Clone impl added in 0.7.1.  Let me know if there is still an issue and we can reopen.

**Comment by Shatur** [comment]
I agree with you. Thanks, will use `clone()`.

**Comment by Shatur** [comment]
> I would expect that the handles to your memory-mapped IO are cheaply clonable. Would it suffice to impl<R> Clone for NpyReader<R> where R: Clone?

It turns out that [Mmap](https://docs.rs/memmap2/latest/memmap2/struct.Mmap.html) is actually aren't clonable :(
To workaround this I have to store `Mmap` in my struct and use something like https://github.com/joshua-maros/ouroboros to reference `&[u8]`.

**Comment by ExpHP** [comment]
(I don't think the issue here is the clonability of Mmap, since it doesn't impl Read)

The more I think about it, I can't even believe that Mmap exposes a `&[u8]`.  This sounds like something that's basically *impossible* to use safely in rust, because unless there is some sort of external access control on the file, another process could always theoretically modify the file at any time.

(and if the point is that the file is allowed to be modified, well, that's a problem, because the optimizer is allowed to assume that a `&[u8]`'s contents don't change for as long as it exists)

> To workaround this I have to store Mmap in my struct and use something like https://github.com/joshua-maros/ouroboros to reference &[u8].

Since the NpyFile itself would need to contain the `&[u8]`, I'm not sure that this is issue is related at all to NpyFile being invalidated by NpyReader.

**Comment by Shatur** [comment]
> (I don't think the issue here is the clonability of Mmap, since it doesn't impl Read)

But `std::io::Cursor<Mmap>` does.

> another process could always theoretically modify the file at any time.

True, this is why memory mapping is unsafe.

> I'm not sure that this is issue is related at all to NpyFile being invalidated by NpyReader.

Unfortunately, this is related because, as I mentioned, I could put `Mmap` in `std::io::Cursor`.

But I'm not sure how to solve this issue on `npyz` side, so I decided to just mention my workaround - store `&[u8]` instead of `Mmap` and self-reference it in a struct. In case other people will read this issue.

**Comment by ExpHP** [comment]
Try this:

```rust
use memmap2::Mmap;
use std::sync::Arc;

#[derive(Debug, Clone)]
struct MmapArc(Arc<Mmap>);

impl MmapArc {
    fn new(mmap: Mmap) -> Self {
        MmapArc(Arc::new(mmap))
    }
}

impl AsRef<[u8]> for MmapArc {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}
```

Thanks to `Arc`, this type can be cloned, and thanks to the `AsRef<[u8]>` impl, `Cursor<MmapArc>` implements `Read + Seek`.

```rust
use std::io::{self, Read};
use memmap2::MmapOptions;
use std::fs::File;

let file = File::open("README.md")?;
let mmap = unsafe { MmapOptions::new().map(&file)? };

let reader = io::Cursor::new(MmapArc::new(mmap));

let mut string1 = String::new();
let mut string2 = String::new();
reader.clone().read_to_string(&mut string1).unwrap();
reader.clone().read_to_string(&mut string2).unwrap();
assert_eq!(string1, string2);
println!("{}", string1);
```
